#!/bin/bash

# Connects to the server using SSH with the private key ~/.ssh/school
# and the user 'ubuntu'

# Server IP address or hostname
server="52.91.116.29"

# SSH command
ssh -i ~/.ssh/school ubuntu@$server

